global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
  - job_name: 'nginx'
    metrics_path: /metrics
    static_configs:
      - targets: ['nginx:8080']